import {
  SiAngular,
  SiBootstrap,
  SiC,
  SiClion,
  SiCplusplus,
  SiCss,
  SiDjango,
  SiDocker,
  SiEspressif,
  SiExpress,
  SiFirebase,
  SiGit,
  SiGithub,
  SiGnubash,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiJira,
  SiJupyter,
  SiKeras,
  SiLatex,
  SiLinux,
  SiMarkdown,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiPandas,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiPytorch,
  SiReact,
  SiSass,
  SiScikitlearn,
  SiStorybook,
  SiSupabase,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
} from "react-icons/si";
import { DiJava } from "react-icons/di";
import { TbBrandAws, TbBrandVscode } from "react-icons/tb";

const ICONS = {
  "c++": SiCplusplus,
  python: SiPython,
  javascript: SiJavascript,
  typescript: SiTypescript,
  c: SiC,
  java: DiJava,
  html: SiHtml5,
  css: SiCss,
  latex: SiLatex,
  markdown: SiMarkdown,

  react: SiReact,
  "next.js": SiNextdotjs,
  angular: SiAngular,
  "material ui": SiMui,
  "tailwind css": SiTailwindcss,
  scss: SiSass,
  bootstrap: SiBootstrap,

  "node.js": SiNodedotjs,
  "express.js": SiExpress,
  django: SiDjango,
  firebase: SiFirebase,
  "firebase realtime database/firestore": SiFirebase,

  postgresql: SiPostgresql,
  "aws rds": TbBrandAws,
  supabase: SiSupabase,
  mongodb: SiMongodb,
  mysql: SiMysql,

  tensorflow: SiTensorflow,
  keras: SiKeras,
  pytorch: SiPytorch,
  "scikit-learn": SiScikitlearn,
  numpy: SiNumpy,
  pandas: SiPandas,

  "esp-32": SiEspressif,

  jest: SiJest,
  storybook: SiStorybook,
  postman: SiPostman,
  git: SiGit,
  github: SiGithub,
  jira: SiJira,
  docker: SiDocker,
  linux: SiLinux,
  "shell scripting": SiGnubash,
  "jupyter notebook": SiJupyter,
  "vs code": TbBrandVscode,
  clion: SiClion,

  "aws ec2": TbBrandAws,
  "aws s3": TbBrandAws,
  "aws iam": TbBrandAws,
  "aws amplify": TbBrandAws,
  "basic ecr/ecs exposure": TbBrandAws,
};

export function getSkillIcon(skill) {
  return ICONS[skill.toLowerCase()] || null;
}
